name: Test utility scripts
on:
  pull_request:
    branches:
      - main

jobs:
  notebooks:

    # get_modified_tutorials.py
    name: "Test get_modified_tutorials.py script"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies and setup
        run: |
          sudo apt-get install pandoc
          python -m pip install -U pip
          python -m pip install gitpython
          git config --global user.email "bot@robot.com"
          git config --global user.name "Botty McBotface"

      # Make sure if a file is removed, it does not appear in the modified list:
      - name: Test 1a - removed (staged)
        run: |
          git rm tutorials/FITS-header/FITS-header.ipynb
          MODIFIED=$(python .github/get_modified_tutorials.py --main-branch origin/main)
          [ ! -z "$MODIFIED" ] && exit 1 || echo "Success!"
          git reset --hard HEAD

      - name: Test 1b - removed and committed
        run: |
          git rm tutorials/FITS-header/FITS-header.ipynb
          git commit -m "TEST COMMIT"
          MODIFIED=$(python .github/get_modified_tutorials.py --main-branch origin/main)
          [ ! -z "$MODIFIED" ] && exit 1 || echo "Success!"
          git reset --hard HEAD~1

      # Make sure if a file is modified, it appears in the modified list:
      - name: Test 2a - edited
        run: |
          cat "TEST" >> tutorials/FITS-header/FITS-header.ipynb
          MODIFIED=$(python .github/get_modified_tutorials.py --main-branch origin/main)
          [ "$MODIFIED" -ne "tutorials/FITS-header/FITS-header.ipynb" ] && exit 1 || echo "Success!"
          git reset --hard HEAD

      - name: Test 2b - edited and staged
        run: |
          cat "TEST" >> tutorials/FITS-header/FITS-header.ipynb
          git add tutorials/FITS-header/FITS-header.ipynb
          MODIFIED=$(python .github/get_modified_tutorials.py --main-branch origin/main)
          [ "$MODIFIED" -ne "tutorials/FITS-header/FITS-header.ipynb" ] && exit 1 || echo "Success!"
          git reset --hard HEAD

      - name: Test 2c - edited and committed
        run: |
          cat "TEST" >> tutorials/FITS-header/FITS-header.ipynb
          git add tutorials/FITS-header/FITS-header.ipynb
          git commit -m "TEST COMMIT"
          MODIFIED=$(python .github/get_modified_tutorials.py --main-branch origin/main)
          [ "$MODIFIED" -ne "tutorials/FITS-header/FITS-header.ipynb" ] && exit 1 || echo "Success!"
          git reset --hard HEAD~1
